# Generated by Django 4.0.3 on 2022-04-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vostok', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='photo1',
        ),
    ]
